name: Testing

on:
  workflow_dispatch

jobs:
  check:
    runs-on: ubuntu-latest
    steps: 
      - name: Print
        run: echo " ${{vars.REPO_VAR}}"
      - name: Print2
        run: echo " ${{secrets.REPO_SECRET}}"
